language: python
python: 3.7.3

- name: Code Climate Coverage Action
  uses: paambaati/codeclimate-action@v2.4.0


before_install:
  - pip install poetry

install:
  - make install

script:
  - make lint
